DECLARE
    WORKER_ID NUMBER := 555;
    WORKER_NAME VARCHAR2(25) := 'DIWANSH';
    BASIC_PAY NUMBER := 48000;
    HRA_AMOUNT NUMBER;

BEGIN
    HRA_AMOUNT := BASIC_PAY * 0.40;

    DBMS_OUTPUT.PUT_LINE('WORKER ID: ' || WORKER_ID);
    DBMS_OUTPUT.PUT_LINE('WORKER NAME: ' || WORKER_NAME);
    DBMS_OUTPUT.PUT_LINE('BASIC PAY: RS. ' || BASIC_PAY);
    DBMS_OUTPUT.PUT_LINE('HOUSE RENT ALLOWANCE: RS. ' || HRA_AMOUNT);

    IF BASIC_PAY > 60000 THEN
        DBMS_OUTPUT.PUT_LINE('TAX APPLICABLE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('TAX NOT APPLICABLE');
    END IF;

END;