CREATE TABLE Students (
      id NUMERIC(10,0) PRIMARY KEY,
      name VARCHAR(50),
      city VARCHAR(30),
      marks NUMERIC(10,0)
  );


  INSERT INTO Students VALUES (1, 'Aman', 'Mohali', 85);
  INSERT INTO Students VALUES (2, 'Rohit', 'Mohali', 78);
  INSERT INTO Students VALUES (3, 'Neha', 'Mohali', 92);
  INSERT INTO Students VALUES (4, 'Simran', 'Amritsar', 88);
  INSERT INTO Students VALUES (5, 'Karan', 'Amritsar', 75);			
  
 



SELECT CITY ,COUNT(*) AS COUNT_STUDNETS
FROM STUDENTS
GROUP BY CITY





SELECT CITY ,COUNT(ID) AS COUNT_STUDNETS
FROM STUDENTS
GROUP BY CITY
ORDER BY COUNT_STUDNETS ASC



SELECT CITY ,COUNT(*) AS COUNT_STUDNETS
FROM STUDENTS
GROUP BY CITY
ORDER BY COUNT(*) ASC




SELECT CITY ,COUNT(ID) AS COUNT_STUDNETS
FROM STUDENTS
GROUP BY CITY
HAVING COUNT(ID)>=3




SELECT CITY ,AVG(MARKS)::NUMERIC(10,2) AS AVERAGE_MARKS
FROM STUDENTS
GROUP BY CITY


