
CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
BOOK_NAME VARCHAR(20) NOT NULL,
AUTHOR_NAME VARCHAR(20) NOT NULL
)



ALTER TABLE BOOKS
ADD BOOK_COUNT INT CHECK(BOOK_COUNT>0) NOT NULL

SELECT * FROM BOOKS

INSERT INTO BOOKS VALUES(101,'HARRY POTER','DAVID',3)


CREATE TABLE LIBRARY_VISITORS(
USER_ID INT PRIMARY KEY,
NAME VARCHAR(20)NOT NULL,
AGE INT CHECK(AGE>=17)NOT NULL,
EMAIL VARCHAR(20)NOT NULL UNIQUE

)

SELECT * FROM LIBRARY_VISITORS

INSERT INTO LIBRARY_VISITORS(USER_ID,NAME,AGE,EMAIL)
VALUES(501,'VANSH SHARMA',18,'schoolcu12@gmail.com')

CREATE TABLE BOOK_ISSUE(
BOOK_ISSUE_ID INT PRIMARY KEY,
USER_ID INT NOT NULL,
BOOK_ID INT NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES LIBRARY_VISITORS(USER_ID),
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID)
)

ALTER TABLE BOOK_ISSUE
ADD ISSUE_DATE DATE

SELECT * FROM BOOK_ISSUE

INSERT INTO BOOK_ISSUE VALUES (1001,501,101,'2026-01-09')

SELECT * FROM BOOK_ISSUE

UPDATE BOOK_ISSUE
SET ISSUE_DATE='2026-01-08'
WHERE BOOK_ISSUE_ID=1001

SELECT * FROM BOOK_ISSUE

CREATE ROLE LIBRARIAN
WITH LOGIN PASSWORD 'PASSWORD12'

GRANT SELECT,INSERT,DELETE,UPDATE ON BOOKS TO LIBRARIAN

GRANT SELECT,INSERT,DELETE,UPDATE ON BOOK_ISSUE TO LIBRARIAN

GRANT SELECT,INSERT,DELETE,UPDATE ON LIBRARY_VISITORS TO LIBRARIAN


